
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-MenuItemReview-EditPage","number":103,"title":"Hl menu item index review edit page","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/103"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization-Edit","number":102,"title":"Kole Organization - Edit page, tests, and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/102"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization-Index","number":101,"title":"Kole Organization Index","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/101"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization-Create","number":100,"title":"Kole Organization - Create Page","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/100"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization-Placeholder","number":99,"title":"Kole organization placeholder","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/99"},{"author":{"id":"U_kgDOBcwKVw","is_bot":false,"login":"JustinZhang809","name":""},"headRefName":"JustinZ-DiningCommonsMenuItems-EditPage","number":97,"title":"JustinZ - Added all the pages for UCSB Dining Commons Menu Items","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/97"},{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-MenuItemReview-CreatePage","number":87,"title":"Hl- menu item review create page","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/87"}]
