
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-MenuItemReview-backend","number":65,"title":"HL - copied MenuItemReview files from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/65"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization","number":64,"title":"Kole Organization - Copy files for backend","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/64"},{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-RecommendationRequest-CreateFixtures","number":63,"title":"AN - recommendation request create fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/63"},{"author":{"id":"U_kgDOBXj98A","is_bot":false,"login":"rmarangoly","name":""},"headRefName":"Rohan-MergeTeam02","number":61,"title":"merging files from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/61"}]
