
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-RecommendationRequest-TableComponent","number":76,"title":"AN - Added Table component with tests for recommendation requests","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/76"},{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-MenuItemReview-Component","number":75,"title":"HL- finished adding component and test for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/75"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"Hao-Articles-TableComponent","number":74,"title":"hy - Articles Table Component and tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/74"},{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-RecommendationRequest-FormComponent","number":73,"title":"AN - Added Form component and tests for Recommendation Request","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/73"}]
