
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBXj98A","is_bot":false,"login":"rmarangoly","name":""},"headRefName":"Rohan-HelpRequest-FormComponent","number":80,"title":"Rohan-HelpRequest Added Form and Tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/80"},{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-RecommendationRequest-CopyPlaceholder","number":79,"title":"An- recommendation request copy placeholder","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/79"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization-Component","number":78,"title":"Kole Organization - Created form, tests, and storybook","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/78"},{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-MenuItemReview-TableComponent","number":77,"title":"Hl - added menu item review table component and test ","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/77"},{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-RecommendationRequest-TableComponent","number":76,"title":"AN - Added Table component with tests for recommendation requests","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-4/pull/76"}]
